package id.atiila.losmantap;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dataNasabah implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Alamat")
	private java.lang.String alamat;
	@org.kie.api.definition.type.Label("Angsuran")
	private java.lang.Integer angsuran;
	@org.kie.api.definition.type.Label("Harga Kendaraan")
	private java.lang.Integer hargaKendaraan;
	@org.kie.api.definition.type.Label("Histori Pembayaran")
	private java.lang.Integer historiPembayaraan;
	@org.kie.api.definition.type.Label("Lama Bekerja")
	private java.lang.Integer lamaBekerja;
	@org.kie.api.definition.type.Label("Nama Cabang")
	private java.lang.String namaCabang;
	@org.kie.api.definition.type.Label("Nama Nasabah")
	private java.lang.String namaNasabah;
	@org.kie.api.definition.type.Label("Pekerjaan")
	private java.lang.String pekerjaan;
	@org.kie.api.definition.type.Label("Pendidikan")
	private java.lang.String pendidikan;
	@org.kie.api.definition.type.Label("Penghasilan Per Bulan")
	private java.lang.Integer penghasilanPerBulan;
	@org.kie.api.definition.type.Label("Portofolio")
	private java.lang.String portofolio;
	@org.kie.api.definition.type.Label("Status Kepemilikan Rumah")
	private java.lang.String statusKepemilikanRumah;
	@org.kie.api.definition.type.Label("Status Pernikahan")
	private java.lang.String statusPernikahan;
	@org.kie.api.definition.type.Label("Tenor")
	private java.lang.Integer tenor;
	@org.kie.api.definition.type.Label("Tanggal Lahir")
	private java.util.Date tglLahir;
	@org.kie.api.definition.type.Label("Uang Muka")
	private java.lang.Integer uangMuka;
	@org.kie.api.definition.type.Label("Skor Pendidikan Pernikahan")
	private java.lang.Integer skorPendidikanPernikahan;
	@org.kie.api.definition.type.Label("Skor Kepemilikan Rumah Pekerjaan")
	private java.lang.Integer skorKepemilikanRumahPekerjaan;
	@org.kie.api.definition.type.Label("Skor Installment OTR Ratio")
	private java.lang.Integer skorInstallmentOTRRatio;
	@org.kie.api.definition.type.Label("Skor Lama Bekerja")
	private java.lang.Integer skorLamaBekerja;
	@org.kie.api.definition.type.Label("Skor LTV")
	private java.lang.Integer skorLTV;
	@org.kie.api.definition.type.Label("Skor Tenor Portofolio")
	private java.lang.Integer skorTenorPortofolio;

	@org.kie.api.definition.type.Label("Skor Total")
	private java.lang.Integer skorTotal;

	@org.kie.api.definition.type.Label("installmentOTR")
	private java.lang.Double installmentOTR;

	@org.kie.api.definition.type.Label("LTV")
	private java.lang.Double ltv;

	@org.kie.api.definition.type.Label("Skor Mobil DSR Tenor")
	private java.lang.Integer skorMobilDSRTenor;

	@org.kie.api.definition.type.Label("Skor Mobil Length of Work")
	private java.lang.Integer skorMobilLengthofWork;

	@org.kie.api.definition.type.Label("Skor Mobil LTV")
	private java.lang.Integer skorMobilLTV;

	@org.kie.api.definition.type.Label("Skor Mobil Marital Home Ownership")
	private java.lang.Integer skorMobilMaritalHomeOwnership;

	@org.kie.api.definition.type.Label("Skor Mobil Monthly Installment Index")
	private java.lang.Integer skorMobilMonthlyInstallmentIndex;

	@org.kie.api.definition.type.Label("Skor Mobil Monthly Installment OTR Portofolio")
	private java.lang.Integer skorMobilMonthlyInstallmentOTRPortofolio;

	@org.kie.api.definition.type.Label("Skor Mobil Occupation Car Age")
	private java.lang.Integer skorMobilOccupationCarAge;

	@org.kie.api.definition.type.Label("DSR")
	private Double dsr;

	@org.kie.api.definition.type.Label("InstallmentIndex")
	private java.lang.Integer installmentIndex;

	@org.kie.api.definition.type.Label("Umur Kendaraan")
	private java.lang.Integer umurKendaraan;

	public dataNasabah() {
	}

	public java.lang.String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(java.lang.String alamat) {
		this.alamat = alamat;
	}

	public java.lang.Integer getAngsuran() {
		return this.angsuran;
	}

	public void setAngsuran(java.lang.Integer angsuran) {
		this.angsuran = angsuran;
	}

	public java.lang.Integer getHargaKendaraan() {
		return this.hargaKendaraan;
	}

	public void setHargaKendaraan(java.lang.Integer hargaKendaraan) {
		this.hargaKendaraan = hargaKendaraan;
	}

	public java.lang.Integer getHistoriPembayaraan() {
		return this.historiPembayaraan;
	}

	public void setHistoriPembayaraan(java.lang.Integer historiPembayaraan) {
		this.historiPembayaraan = historiPembayaraan;
	}

	public java.lang.Integer getLamaBekerja() {
		return this.lamaBekerja;
	}

	public void setLamaBekerja(java.lang.Integer lamaBekerja) {
		this.lamaBekerja = lamaBekerja;
	}

	public java.lang.String getNamaCabang() {
		return this.namaCabang;
	}

	public void setNamaCabang(java.lang.String namaCabang) {
		this.namaCabang = namaCabang;
	}

	public java.lang.String getNamaNasabah() {
		return this.namaNasabah;
	}

	public void setNamaNasabah(java.lang.String namaNasabah) {
		this.namaNasabah = namaNasabah;
	}

	public java.lang.String getPekerjaan() {
		return this.pekerjaan;
	}

	public void setPekerjaan(java.lang.String pekerjaan) {
		this.pekerjaan = pekerjaan;
	}

	public java.lang.String getPendidikan() {
		return this.pendidikan;
	}

	public void setPendidikan(java.lang.String pendidikan) {
		this.pendidikan = pendidikan;
	}

	public java.lang.Integer getPenghasilanPerBulan() {
		return this.penghasilanPerBulan;
	}

	public void setPenghasilanPerBulan(java.lang.Integer penghasilanPerBulan) {
		this.penghasilanPerBulan = penghasilanPerBulan;
	}

	public java.lang.String getPortofolio() {
		return this.portofolio;
	}

	public void setPortofolio(java.lang.String portofolio) {
		this.portofolio = portofolio;
	}

	public java.lang.String getStatusKepemilikanRumah() {
		return this.statusKepemilikanRumah;
	}

	public void setStatusKepemilikanRumah(
			java.lang.String statusKepemilikanRumah) {
		this.statusKepemilikanRumah = statusKepemilikanRumah;
	}

	public java.lang.String getStatusPernikahan() {
		return this.statusPernikahan;
	}

	public void setStatusPernikahan(java.lang.String statusPernikahan) {
		this.statusPernikahan = statusPernikahan;
	}

	public java.lang.Integer getTenor() {
		return this.tenor;
	}

	public void setTenor(java.lang.Integer tenor) {
		this.tenor = tenor;
	}

	public java.util.Date getTglLahir() {
		return this.tglLahir;
	}

	public void setTglLahir(java.util.Date tglLahir) {
		this.tglLahir = tglLahir;
	}

	public java.lang.Integer getUangMuka() {
		return this.uangMuka;
	}

	public void setUangMuka(java.lang.Integer uangMuka) {
		this.uangMuka = uangMuka;
	}

	public java.lang.Integer getSkorPendidikanPernikahan() {
		return this.skorPendidikanPernikahan;
	}

	public void setSkorPendidikanPernikahan(
			java.lang.Integer skorPendidikanPernikahan) {
		this.skorPendidikanPernikahan = skorPendidikanPernikahan;
	}

	public java.lang.Integer getSkorKepemilikanRumahPekerjaan() {
		return this.skorKepemilikanRumahPekerjaan;
	}

	public void setSkorKepemilikanRumahPekerjaan(
			java.lang.Integer skorKepemilikanRumahPekerjaan) {
		this.skorKepemilikanRumahPekerjaan = skorKepemilikanRumahPekerjaan;
	}

	public java.lang.Integer getSkorInstallmentOTRRatio() {
		return this.skorInstallmentOTRRatio;
	}

	public void setSkorInstallmentOTRRatio(
			java.lang.Integer skorInstallmentOTRRatio) {
		this.skorInstallmentOTRRatio = skorInstallmentOTRRatio;
	}

	public java.lang.Integer getSkorLamaBekerja() {
		return this.skorLamaBekerja;
	}

	public void setSkorLamaBekerja(java.lang.Integer skorLamaBekerja) {
		this.skorLamaBekerja = skorLamaBekerja;
	}

	public java.lang.Integer getSkorLTV() {
		return this.skorLTV;
	}

	public void setSkorLTV(java.lang.Integer skorLTV) {
		this.skorLTV = skorLTV;
	}

	public java.lang.Integer getSkorTenorPortofolio() {
		return this.skorTenorPortofolio;
	}

	public void setSkorTenorPortofolio(java.lang.Integer skorTenorPortofolio) {
		this.skorTenorPortofolio = skorTenorPortofolio;
	}

	public java.lang.Integer getSkorTotal() {
		return this.skorTotal;
	}

	public void setSkorTotal(java.lang.Integer skorTotal) {
		this.skorTotal = skorTotal;
	}

	public java.lang.Double getInstallmentOTR() {
		return this.installmentOTR;
	}

	public void setInstallmentOTR(java.lang.Double installmentOTR) {
		this.installmentOTR = installmentOTR;
	}

	public java.lang.Double getLtv() {
		return this.ltv;
	}

	public void setLtv(java.lang.Double ltv) {
		this.ltv = ltv;
	}

	public java.lang.Integer getSkorMobilDSRTenor() {
		return this.skorMobilDSRTenor;
	}

	public void setSkorMobilDSRTenor(java.lang.Integer skorMobilDSRTenor) {
		this.skorMobilDSRTenor = skorMobilDSRTenor;
	}

	public java.lang.Integer getSkorMobilLengthofWork() {
		return this.skorMobilLengthofWork;
	}

	public void setSkorMobilLengthofWork(java.lang.Integer skorMobilLengthofWork) {
		this.skorMobilLengthofWork = skorMobilLengthofWork;
	}

	public java.lang.Integer getSkorMobilLTV() {
		return this.skorMobilLTV;
	}

	public void setSkorMobilLTV(java.lang.Integer skorMobilLTV) {
		this.skorMobilLTV = skorMobilLTV;
	}

	public java.lang.Integer getSkorMobilMaritalHomeOwnership() {
		return this.skorMobilMaritalHomeOwnership;
	}

	public void setSkorMobilMaritalHomeOwnership(
			java.lang.Integer skorMobilMaritalHomeOwnership) {
		this.skorMobilMaritalHomeOwnership = skorMobilMaritalHomeOwnership;
	}

	public java.lang.Integer getSkorMobilMonthlyInstallmentIndex() {
		return this.skorMobilMonthlyInstallmentIndex;
	}

	public void setSkorMobilMonthlyInstallmentIndex(
			java.lang.Integer skorMobilMonthlyInstallmentIndex) {
		this.skorMobilMonthlyInstallmentIndex = skorMobilMonthlyInstallmentIndex;
	}

	public java.lang.Integer getSkorMobilMonthlyInstallmentOTRPortofolio() {
		return this.skorMobilMonthlyInstallmentOTRPortofolio;
	}

	public void setSkorMobilMonthlyInstallmentOTRPortofolio(
			java.lang.Integer skorMobilMonthlyInstallmentOTRPortofolio) {
		this.skorMobilMonthlyInstallmentOTRPortofolio = skorMobilMonthlyInstallmentOTRPortofolio;
	}

	public java.lang.Integer getSkorMobilOccupationCarAge() {
		return this.skorMobilOccupationCarAge;
	}

	public void setSkorMobilOccupationCarAge(
			java.lang.Integer skorMobilOccupationCarAge) {
		this.skorMobilOccupationCarAge = skorMobilOccupationCarAge;
	}

	public java.lang.Integer getInstallmentIndex() {
		return this.installmentIndex;
	}

	public void setInstallmentIndex(java.lang.Integer installmentIndex) {
		this.installmentIndex = installmentIndex;
	}

	public java.lang.Integer getUmurKendaraan() {
		return this.umurKendaraan;
	}

	public java.lang.Integer getMinimalAge() {
		java.util.Date now = new java.util.Date();

		long diff = now.getTime() - this.tglLahir.getTime();

		Long days = diff / (24 * 60 * 60 * 1000) + 1;

		return days.intValue() / 365;
	}

	public void setUmurKendaraan(java.lang.Integer umurKendaraan) {
		this.umurKendaraan = umurKendaraan;
	}

	public java.lang.Double getDsr() {
		return this.dsr;
	}

	public void setDsr(java.lang.Double dsr) {
		this.dsr = dsr;
	}

	public dataNasabah(java.lang.String alamat, java.lang.Integer angsuran,
			java.lang.Integer hargaKendaraan,
			java.lang.Integer historiPembayaraan,
			java.lang.Integer lamaBekerja, java.lang.String namaCabang,
			java.lang.String namaNasabah, java.lang.String pekerjaan,
			java.lang.String pendidikan, java.lang.Integer penghasilanPerBulan,
			java.lang.String portofolio,
			java.lang.String statusKepemilikanRumah,
			java.lang.String statusPernikahan, java.lang.Integer tenor,
			java.util.Date tglLahir, java.lang.Integer uangMuka,
			java.lang.Integer skorPendidikanPernikahan,
			java.lang.Integer skorKepemilikanRumahPekerjaan,
			java.lang.Integer skorInstallmentOTRRatio,
			java.lang.Integer skorLamaBekerja, java.lang.Integer skorLTV,
			java.lang.Integer skorTenorPortofolio, java.lang.Integer skorTotal,
			java.lang.Double installmentOTR, java.lang.Double ltv,
			java.lang.Integer skorMobilDSRTenor,
			java.lang.Integer skorMobilLengthofWork,
			java.lang.Integer skorMobilLTV,
			java.lang.Integer skorMobilMaritalHomeOwnership,
			java.lang.Integer skorMobilMonthlyInstallmentIndex,
			java.lang.Integer skorMobilMonthlyInstallmentOTRPortofolio,
			java.lang.Integer skorMobilOccupationCarAge, java.lang.Double dsr,
			java.lang.Integer installmentIndex, java.lang.Integer umurKendaraan) {
		this.alamat = alamat;
		this.angsuran = angsuran;
		this.hargaKendaraan = hargaKendaraan;
		this.historiPembayaraan = historiPembayaraan;
		this.lamaBekerja = lamaBekerja;
		this.namaCabang = namaCabang;
		this.namaNasabah = namaNasabah;
		this.pekerjaan = pekerjaan;
		this.pendidikan = pendidikan;
		this.penghasilanPerBulan = penghasilanPerBulan;
		this.portofolio = portofolio;
		this.statusKepemilikanRumah = statusKepemilikanRumah;
		this.statusPernikahan = statusPernikahan;
		this.tenor = tenor;
		this.tglLahir = tglLahir;
		this.uangMuka = uangMuka;
		this.skorPendidikanPernikahan = skorPendidikanPernikahan;
		this.skorKepemilikanRumahPekerjaan = skorKepemilikanRumahPekerjaan;
		this.skorInstallmentOTRRatio = skorInstallmentOTRRatio;
		this.skorLamaBekerja = skorLamaBekerja;
		this.skorLTV = skorLTV;
		this.skorTenorPortofolio = skorTenorPortofolio;
		this.skorTotal = skorTotal;
		this.installmentOTR = installmentOTR;
		this.ltv = ltv;
		this.skorMobilDSRTenor = skorMobilDSRTenor;
		this.skorMobilLengthofWork = skorMobilLengthofWork;
		this.skorMobilLTV = skorMobilLTV;
		this.skorMobilMaritalHomeOwnership = skorMobilMaritalHomeOwnership;
		this.skorMobilMonthlyInstallmentIndex = skorMobilMonthlyInstallmentIndex;
		this.skorMobilMonthlyInstallmentOTRPortofolio = skorMobilMonthlyInstallmentOTRPortofolio;
		this.skorMobilOccupationCarAge = skorMobilOccupationCarAge;
		this.dsr = dsr;
		this.installmentIndex = installmentIndex;
		this.umurKendaraan = umurKendaraan;
	}

}